### ISSUE TITLE
Responsive Design component publication

### ISSUE THREAD

**Issue by DanielPaezb** [Dvs-Projects/Classic-Instagram-Clone#16]

**Comment by Nicolas-alt** [comment]
Duplicated [at](https://github.com/Dvs-Projects/Classic-Instagram-Clone/issues/9)

**Comment by Nicolas-alt** [comment]
@DanielPaezb  Please read the all the comments before opening or closing issues, so as not to generate chaos with the follow-up  i told you [here](https://github.com/Dvs-Projects/Classic-Instagram-Clone/issues/9)
